### ISSUE TITLE
Xls error: Cfb error: Codepage 5212 not found

### ISSUE THREAD

**Issue by thetopic** [tafia/calamine#193] opened 2020-11-25 11:01 UTC
When I open some excel file I have this error : Xls error: Cfb error: Codepage 5212 not found.

It seems that this problem has existed on other projects : [https://github.com/zdavatz/spreadsheet/pull/161](https://github.com/zdavatz/spreadsheet/pull/161)

**Comment by tafia** [comment] 2022-10-19 16:12
Closing as I can't reproduce without a file.

**Closed by tafia** 2022-10-19 16:12 UTC
