### ISSUE TITLE
[BUG]: XLSB reader panic`s on some Named Ranges

### ISSUE THREAD

**Issue by kkirsanov** [tafia/calamine#184] opened 2020-09-24 07:26 UTC
Using this named range results in error:
![image](https://user-images.githubusercontent.com/1369246/94113425-88402c80-fe4f-11ea-8b26-ac4bf126fb12.png)
in
`xlsb.rs 865: formula.push_str(&names[iname].0);`

Because the formula was not correctly parsed in `parse_formula` function. As a result, the `iname` index points outside the range.

I'm new to RUST and XLSB, so I can't fix it on my own. Hust ignoring an index out of range doesn't seem like a pretty solution

**Comment by kkirsanov** [comment] 2020-09-24 07:34
Sample xlsb with error - https://www.dropbox.com/s/3eyp8d95484jiki/bug2.xlsb?dl=0

**Comment by tafia** [comment] 2022-10-19 16:26
Closing as I cannot reproduce. It has probably been fixed since then.

**Closed by tafia** 2022-10-19 16:26 UTC
