### ISSUE TITLE
Garbled characters

### ISSUE THREAD

**Issue by chengmiaook** [tafia/calamine#442] opened 2024-06-13 08:59 UTC
I use workbook.worksheet_range to read the excel, but i get Garbled characters   ，for example   String("姊﹀够瑗挎父")，help please

**Comment by jqnatividad** [comment] 2024-06-19 22:52
Can you add a sample worksheet and corresponding code you're using?

**Comment by tafia** [comment] 2024-07-08 16:23
Closing as we cannot reproduce without an example.

**Closed** 2024-07-08 16:23 UTC
